import { createTypes } from 'reduxsauce'

export default createTypes(`
    APP_OPENED,

    FETCH_CATALOG,
    FETCH_CATALOG_REQ,
    FETCH_CATALOG_SUCC,
    FETCH_CATALOG_ERR,
    FETCH_CATALOG_SAVE,
    FETCH_CATALOG_END,

    SOCKET_STOCK_CHANGED,
    FETCH_STOCK,
    FETCH_STOCK_ESC,
    FETCH_STOCK_REQ,
    FETCH_STOCK_ERR,
    FETCH_STOCK_SAVE,
    FETCH_STOCK_END,

    FETCH_PRICES,
    FETCH_PRICES_ESC,
    FETCH_PRICES_REQ,
    FETCH_PRICES_ERR,
    FETCH_PRICES_SAVE,
    FETCH_PRICES_END
`)
